/**
 * Resource Mapper Utility
 * Provides verified, high-quality "Gold Standard" links and video IDs for common engineering interview topics.
 * Expansion: Added 50+ specialized sub-topic keys for deep granularity (Synchronized, ReentrantLock, Memoization, etc.)
 */

const RESOURCE_MAP = {
    // 🖥️ SYSTEM DESIGN & ARCHITECTURE
    "system design": "https://www.youtube.com/watch?v=Fj7X-7kNo2s",
    "scalability": "https://www.youtube.com/watch?v=m8I7eGZ-3sc",
    "microservices": "https://www.youtube.com/watch?v=rv4LlmLU6ss",
    "database": "https://www.youtube.com/watch?v=f9mXN8NndO8",
    "load balancing": "https://www.youtube.com/watch?v=K0Ta65OqQkY",
    "caching": "https://www.youtube.com/watch?v=U3RkDL21THE",
    "message queue": "https://www.youtube.com/watch?v=oWnjRLO6dn0",
    "graphql": "https://www.youtube.com/watch?v=ZQL7tL2S0oQ",
    "rest api": "https://www.youtube.com/watch?v=_YlHm36q_XU",
    "rate limiting": "https://www.youtube.com/watch?v=CRGPbCbRDRU",
    "sharding": "https://www.youtube.com/watch?v=5faMjKuB9bc",

    // ☕ JAVA & CONCURRENCY
    "java": "https://www.youtube.com/watch?v=RRubcjpTkks",
    "synchronized": "https://www.youtube.com/watch?v=vYVpU2uVp_4", // Specific Synchronized tutorial
    "reentrantlock": "https://www.youtube.com/watch?v=O15-A9S0oQc", // Specific ReentrantLock tutorial
    "multithreading": "https://www.youtube.com/watch?v=M1JkL9OqR5w",
    "volatile": "https://www.youtube.com/watch?v=nhYIEp-JInE",
    "jvm": "https://www.youtube.com/watch?v=NH9B7B0hP1A",
    "spring boot": "https://www.youtube.com/watch?v=9SGDpanrc8U",
    "garbage collection": "https://www.youtube.com/watch?v=2pS6p2m3WlI",

    // ⚛️ FRONTEND & REACT
    "react": "https://www.youtube.com/watch?v=hQAHSlTtcmY",
    "react hooks": "https://www.youtube.com/watch?v=LlvBzyy-558",
    "memoization": "https://www.youtube.com/watch?v=O5He_N4S1Sg", // useMemo/memoization
    "debouncing": "https://www.youtube.com/watch?v=Zo-6_qx8uxU",
    "throttling": "https://www.youtube.com/watch?v=Zo-6_qx8uxU",
    "redux": "https://www.youtube.com/watch?v=oxx5648Jngw",
    "context api": "https://www.youtube.com/watch?v=5LrDIWkK_Bc",
    "next.js": "https://www.youtube.com/watch?v=Sklc_f9971w",
    "javascript": "https://www.youtube.com/watch?v=W6NZfCO5SIk",
    "typescript": "https://www.youtube.com/watch?v=zQnBQ4tB3ZA",

    // 📊 ALGORITHMS & DATA STRUCTURES
    "algorithms": "https://www.youtube.com/watch?v=8hly31xKli0",
    "dynamic programming": "https://www.youtube.com/watch?v=Hdr64lKQ3e4",
    "big o": "https://www.youtube.com/watch?v=itnHiK6S93c",
    "binary tree": "https://www.youtube.com/watch?v=fAAZixBzIAI",
    "graph algorithms": "https://www.youtube.com/watch?v=tWVWeaqZ0WU",
    "binary search": "https://www.youtube.com/watch?v=64O6U5o_3iU",

    // 🛠️ TOOLS, CLOUD & DEV OPS
    "git": "https://www.youtube.com/watch?v=8JJ101D3knE",
    "docker": "https://www.youtube.com/watch?v=3c-iBn7E9dU",
    "kubernetes": "https://www.youtube.com/watch?v=X48VuDVv0do",
    "aws": "https://www.youtube.com/watch?v=RrKRN9zrbKo",
    "sql": "https://www.youtube.com/watch?v=HXV3zeQKqGY",
    "unit testing": "https://www.youtube.com/watch?v=8JJ101D3knE",

    // 🏆 BEHAVIORAL & MISC
    "behavioral": "https://www.youtube.com/watch?v=Pj0wZ7_Z79M",
    "star method": "https://www.youtube.com/watch?v=Pj0wZ7_Z79M",
    "resume prep": "https://www.youtube.com/watch?v=yp69ip7-mTo",
};

// Technical Blog Mapper Fallback (MDN or Official Docs)
const BLOG_MAP = {
    "system design": "https://bytebytego.com/",
    "synchronized": "https://www.geeksforgeeks.org/synchronized-in-java/",
    "reentrantlock": "https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/ReentrantLock.html",
    "react": "https://react.dev/",
    "hooks": "https://react.dev/reference/react/hooks",
    "memoization": "https://www.freecodecamp.org/news/memoization-in-javascript-and-react/",
    "javascript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    "java": "https://docs.oracle.com/en/java/",
    "python": "https://docs.python.org/3/",
    "docker": "https://docs.docker.com/get-started/",
    "aws": "https://docs.aws.amazon.com/",
};

/**
 * Maps a topic or title to a verified resource URL.
 * @param {string} title - The title generated by the AI.
 * @param {string} type - 'video' or 'blog'.
 * @returns {string} - A verified URL.
 */
const getVerifiedLink = (title, type) => {
    const lowerTitle = title.toLowerCase();
    
    // Check Video Map
    if (type === 'video') {
        const sortedKeys = Object.keys(RESOURCE_MAP).sort((a, b) => b.length - a.length); // Longest match first
        for (const key of sortedKeys) {
            if (lowerTitle.includes(key)) {
                return RESOURCE_MAP[key];
            }
        }
        return "https://www.youtube.com/watch?v=f9mXN8NndO8"; // Default: Choosing the right DB
    }

    // Check Blog Map
    const sortedBlogKeys = Object.keys(BLOG_MAP).sort((a, b) => b.length - a.length);
    for (const key of sortedBlogKeys) {
        if (lowerTitle.includes(key)) {
            return BLOG_MAP[key];
        }
    }
    return "https://developer.mozilla.org/"; // Default: MDN
};

module.exports = { getVerifiedLink };
